const mongoose = require('mongoose')

const ProfilRecruteur = new mongoose.Schema({
name:{
    type:String,
    required:true
},
lastName:{
    type:String,
    required:true
},
email:{
    type:String,
    required:true,
    unique:true},
    civilité:{
        type:String,

    },
    DateNaissance:{
        type:String,},
        Gouvernorat:{
            type:String,
            required:true
        },
        Github:{
            type:String,
            
        },
        LinkedIn:{
            type:String,
        },
        website:{
            type:String,
        },
        ExperienceExperience:[
            {
                Entreprise:{
                    type:String,
                    required:true
                },
                Poste:{
                    type:String,
                    required:true
                },
                DateDebut:{
                    type:String,
                    required:true
                },
                DateFin:{
                    type:String,
                    required:true
                },
                Description:{
                    type:String,
                    required:true
                }}
        ],
        Formation:[
            {
                Diplome:{
                    type:String,
                    required:true
                },
                Ecole:{
                    type:String,
                    required:true
                },
                DateDebut:{
                    type:String,
                    required:true
                },
                DateFin:{
                    type:String,
                    required:true
                },
                Description:{
                    type:String,
                    required:true
                }
            }],
            Competence:[
                {
                    Nom:{
                        type:String,
                        required:true
                    },
                    Niveau:{
                        type:String,
                        required:true
                    }
                }],
                Langue:[
                    {
                        Nom:{
                            type:String,
                            required:true
                        },
                        Niveau:{
                            type:String,
                            required:true
                        }}]

})

module.exports = mongoose.model('ProfilRecruteur',ProfilRecruteur)